spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/coffeeRoast
    driver-class-name: org.postgresql.Driver